version: '2'

services:
  tomcat:
    # Build action should be successful from any RHEL Host system running the Docker service with subscription managed registered
    # + info: https://access.redhat.com/solutions/253273
    build: .
    ports:
      - '8080:8080'
    volumes:
      - 'tomcat_data:/bitnami'

volumes:
  tomcat_data:
    driver: local
